/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package books;
import  java.util.Date ;
import static books.managelecteurs.isNumeric;
import static books.managelecteurs.isemail;
import dao.ConnectionProvider;
import dao.DbOperations;
import dao.readDao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.reader;
import java.sql.*;

/**
 *
 * @author user
 */
public class emprunter extends javax.swing.JFrame {

    /**
     * Creates new form emprunter
     */
    public emprunter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        isbnrech = new javax.swing.JTextField();
        bookname = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cinrech = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        bookcount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        issuedate = new rojeru_san.componentes.RSDateChooser();
        duedate = new rojeru_san.componentes.RSDateChooser();
        issuebook = new rojeru_san.complementos.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 231, 228));

        jPanel2.setBackground(new java.awt.Color(28, 38, 61));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText(" Book  details");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ISBN:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Book Name:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Author:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity:");

        isbnrech.setEditable(false);
        isbnrech.setBackground(new java.awt.Color(28, 38, 61));
        isbnrech.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        isbnrech.setForeground(new java.awt.Color(255, 255, 255));
        isbnrech.setBorder(null);

        bookname.setEditable(false);
        bookname.setBackground(new java.awt.Color(28, 38, 61));
        bookname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bookname.setForeground(new java.awt.Color(255, 255, 255));
        bookname.setBorder(null);

        author.setEditable(false);
        author.setBackground(new java.awt.Color(28, 38, 61));
        author.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        author.setForeground(new java.awt.Color(255, 255, 255));
        author.setBorder(null);

        quantity.setEditable(false);
        quantity.setBackground(new java.awt.Color(28, 38, 61));
        quantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        quantity.setForeground(new java.awt.Color(255, 255, 255));
        quantity.setBorder(null);

        m1.setEditable(false);
        m1.setBackground(new java.awt.Color(28, 38, 61));
        m1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 51, 51));
        m1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m1.setBorder(null);

        back.setBackground(new java.awt.Color(67, 91, 123));
        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Rewind_48px.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookname)
                            .addComponent(author)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(isbnrech, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 31, Short.MAX_VALUE))
                            .addComponent(quantity))))
                .addGap(77, 77, 77))
            .addComponent(m1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(isbnrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(67, 91, 123));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Student_Registration_100px_2.png"))); // NOI18N
        jLabel1.setText("member  details");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CIN:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Firstname:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("phonenumber:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LastName:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("email:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("status:");

        cinrech.setEditable(false);
        cinrech.setBackground(new java.awt.Color(67, 91, 123));
        cinrech.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cinrech.setForeground(new java.awt.Color(255, 255, 255));
        cinrech.setBorder(null);
        cinrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinrechActionPerformed(evt);
            }
        });

        firstname.setEditable(false);
        firstname.setBackground(new java.awt.Color(67, 91, 123));
        firstname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setBorder(null);
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        lastname.setEditable(false);
        lastname.setBackground(new java.awt.Color(67, 91, 123));
        lastname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastname.setForeground(new java.awt.Color(255, 255, 255));
        lastname.setBorder(null);

        phonenumber.setEditable(false);
        phonenumber.setBackground(new java.awt.Color(67, 91, 123));
        phonenumber.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phonenumber.setForeground(new java.awt.Color(255, 255, 255));
        phonenumber.setBorder(null);

        email.setEditable(false);
        email.setBackground(new java.awt.Color(67, 91, 123));
        email.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);

        status.setEditable(false);
        status.setBackground(new java.awt.Color(67, 91, 123));
        status.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setBorder(null);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        m2.setEditable(false);
        m2.setBackground(new java.awt.Color(67, 91, 123));
        m2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 51, 51));
        m2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m2.setBorder(null);
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("bookcount:");

        bookcount.setEditable(false);
        bookcount.setBackground(new java.awt.Color(67, 91, 123));
        bookcount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bookcount.setForeground(new java.awt.Color(255, 255, 255));
        bookcount.setBorder(null);
        bookcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookcountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastname)
                                    .addComponent(phonenumber)
                                    .addComponent(email)
                                    .addComponent(cinrech)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(status)
                                    .addComponent(bookcount))))))
                .addGap(29, 29, 29))
            .addComponent(m2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cinrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(58, 58, 58)
                .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 38, 61));
        jLabel3.setText("Issue Book");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("CIN:");

        cin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFocusLost(evt);
            }
        });
        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("ISBN:");

        isbn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        isbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                isbnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                isbnFocusLost(evt);
            }
        });
        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Issue Date:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Due Date:");

        issuedate.setColorBackground(new java.awt.Color(67, 91, 123));
        issuedate.setColorForeground(new java.awt.Color(28, 38, 61));
        issuedate.setPlaceholder("Select issue Date");

        duedate.setColorBackground(new java.awt.Color(67, 91, 123));
        duedate.setColorForeground(new java.awt.Color(28, 38, 61));
        duedate.setPlaceholder("Select Due Date");

        issuebook.setBackground(new java.awt.Color(67, 91, 123));
        issuebook.setText("Issue Book");
        issuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(137, 137, 137))
                    .addComponent(issuebook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(issuebook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean isNumeric(String str) { 
        
   return str.matches("[-+]?[0-9]+"); 
   
}
public boolean issueBook() throws SQLException {
    Boolean issue ;
 try {
    
    int bookid = Integer.parseInt(isbn.getText().trim());
    int readerid = Integer.parseInt(cin.getText().trim());
    Connection con=ConnectionProvider.getCon();
    PreparedStatement pst=con.prepareStatement("select * from  emprunt where isbn=? and cin=?;");
    pst.setInt(1,bookid);
    pst.setInt(2,readerid);
    ResultSet rs=pst.executeQuery();
    while(rs.next()){
        if(!rs.getBoolean("status"))
            
            throw(new Exception("this user has no right to issue this book "));
           
             
        }
        
        
        
    Date sissuedate = issuedate.getDatoFecha();
    Date sduedate = duedate.getDatoFecha();

    // Convert java.util.Date to java.sql.Date
    java.sql.Date sissueDate = new java.sql.Date(sissuedate.getTime());
    java.sql.Date sdueDate = new java.sql.Date(sduedate.getTime());

   
         con = ConnectionProvider.getCon();
        String sql = "INSERT INTO emprunt (cin, isbn, date_emprunt, date_retour, status) VALUES (?, ?, ?, ?, ?)";
        pst = con.prepareStatement(sql);
        pst.setInt(1, readerid);
        pst.setLong(2, bookid);
        pst.setDate(3, sissueDate); // Set date_emprunt
        pst.setDate(4, sdueDate); // Set date_retour
        pst.setBoolean(5, false); // Set status
        int rowCount = pst.executeUpdate();
        if (rowCount > 0) {
            issue = true;
            updatemember();
            updateBook();
        } else {
            issue = false;
        }
    } catch (Exception e) {
        
            JOptionPane.showMessageDialog(null, e);
            issue = false; 
          
        
    }
    
    return issue;
}

//fetch book details from database and display it in the book detail panel
public void getBook(){
    int bookid = Integer.parseInt(isbn.getText().trim());

    try{
        
        Connection con=ConnectionProvider.getCon();
        PreparedStatement pst=con.prepareStatement("select * from  books where ISBN=?;");
        pst.setInt(1,bookid);
        
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
             m1.setText("");
            issuebook.setEnabled(true);
            isbnrech.setText(rs.getString("ISBN"));
            bookname.setText(rs.getString("titre"));
            author.setText(rs.getString("auteur"));
            quantity.setText(rs.getString("quantity"));
        }
        else{
             m1.setText("invalid isbn!!!");
             issuebook.setEnabled(false);
        }
        
        
    }catch(Exception e){
        e.printStackTrace();
        
    }
    
    
}
public void updateBook(){
 
    Long bookid= Long.valueOf(isbn.getText());
    try{
        Connection con=ConnectionProvider.getCon();
        String sql="update books set quantity =quantity-1 where ISBN=?;";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setLong(1,bookid);
        
        int rs=pst.executeUpdate();
        if(rs>0){
            JOptionPane.showMessageDialog(null,"book quantity updated " );
            int q=Integer.parseInt(quantity.getText());
            quantity.setText(Integer.toString(q-1));
             
        }
        else{
            JOptionPane.showMessageDialog(null,"can't update book qte " );
        }
        
        
        
    }catch(Exception e){
        e.printStackTrace();
        
    }
    
    
    
    
}
public void updatemember(){
    
    int readid= Integer.parseInt(cin.getText());
    try{
        Connection con=ConnectionProvider.getCon();
        String sql="update lecteur set book_count =book_count-1 where CIN=?;";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setInt(1,readid);
        
        int rs=pst.executeUpdate();
        if(rs>0){
            JOptionPane.showMessageDialog(null,"book_count updated " );
            int q=Integer.parseInt(bookcount.getText());
            bookcount.setText(Integer.toString(q-1));
             
        }
        else{
            JOptionPane.showMessageDialog(null,"can't update book count " );
        }
        
        
        
    }catch(Exception e){
        e.printStackTrace();
        
    }
    
    
    
    
}
public void getreader(){
    int readid =Integer.parseInt(cin.getText().trim());

    try{
        Connection con=ConnectionProvider.getCon();
        PreparedStatement pst=con.prepareStatement("select * from lecteur where cin=?;");
        pst.setInt(1,readid); 
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
            m2.setText("");
            issuebook.setEnabled(true);
            bookcount.setText(rs.getString("book_count"));
            cinrech.setText(rs.getString("cin"));
            firstname.setText(rs.getString("nom"));
            lastname.setText(rs.getString("prenom"));
            email.setText(rs.getString("email"));
            phonenumber.setText(rs.getString("phonenumber"));
            if(Integer.parseInt(rs.getString("status"))== 1) {
                status.setText("a le droit d'emprunter");
                issuebook.setEnabled(true);
            }
            else{
                status.setText("pas droit d'emprunter");
                issuebook.setEnabled(false);
                
            }
        }
        else{
            m2.setText("invalid cin!!!");
            issuebook.setEnabled(false);
        }
        
        
    }catch(Exception e){
        e.printStackTrace();
        
    }
    
    
}
    private void cinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusGained

    }//GEN-LAST:event_cinFocusGained

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
       if(!cin.getText().equals(""))
           getreader(); 
    }//GEN-LAST:event_cinFocusLost

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed

    }//GEN-LAST:event_cinActionPerformed

    private void isbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_isbnFocusGained

    }//GEN-LAST:event_isbnFocusGained

    private void isbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_isbnFocusLost
       if(!isbn.getText().equals(""))
           getBook(); 
    }//GEN-LAST:event_isbnFocusLost

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed

    }//GEN-LAST:event_isbnActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void cinrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinrechActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void issuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebookActionPerformed
       try{
           
           if(cin.getText().trim().equals("") || !isNumeric(cin.getText().trim())){
                throw(new Exception("give Cin must ba a number "));
            }
            if(isbn.getText().trim().equals("") || !isNumeric(isbn.getText().trim())){
                throw(new Exception("give Cin must ba a number "));
            }
            if(quantity.getText().equals("0")){
                throw(new Exception("this book is not avalaible "));
           
       }
            if(bookcount.getText().equals("0")){
                throw(new Exception("this member doesn't have the right to issue a book "));
                
            }
            Date uissuedate= issuedate.getDatoFecha();
            Date  uduedate=duedate.getDatoFecha();
            if(uduedate.compareTo(uissuedate)<0 ){
                throw(new Exception("Due date must be after issue date "));  
            }
        
        
        if(issueBook()){
           JOptionPane.showMessageDialog(this,"book issued successfully");
          
           
       }
       else{
           JOptionPane.showMessageDialog(this,"can't issue the book");
           
       }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
           
       }
    }//GEN-LAST:event_issuebookActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // home page
    }//GEN-LAST:event_backActionPerformed

    private void bookcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookcountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookcountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emprunter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emprunter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emprunter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emprunter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emprunter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JButton back;
    private javax.swing.JTextField bookcount;
    private javax.swing.JTextField bookname;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField cinrech;
    private rojeru_san.componentes.RSDateChooser duedate;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField isbn;
    private javax.swing.JTextField isbnrech;
    private rojeru_san.complementos.RSButtonHover issuebook;
    private rojeru_san.componentes.RSDateChooser issuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
