/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package books;

import dao.ConnectionProvider;
import dao.DbOperations;
import dao.readDao;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.reader;
import model.tableread;
import java.sql.*;

/**
 *
 * @author user
 */
public class managelecteurs extends javax.swing.JFrame {
    int  status;
    /**
     * Creates new form managelecteurs
     */
    public managelecteurs() {
        
        initComponents();
        addPlaceholderStyle(cin);
        addPlaceholderStyle(firstname);
        addPlaceholderStyle(lastname);
        addPlaceholderStyle(email);
        addPlaceholderStyle(phonenumber);
        addPlaceholderStyle(search);
        addPlaceholderStyle(status1);
        status1.setEnabled(false);
        addPlaceholderStyle(bookcount);
        bookcount.setEnabled(false);
        
        showread();

    }

    public ArrayList<reader> getreadList() throws SQLException{
      ArrayList<reader>  readers =new ArrayList<reader>();
       Connection con = ConnectionProvider.getCon();
       String query ="select * from lecteur";
       Statement st;
       ResultSet rs;
       st=con.createStatement();
       rs=st.executeQuery(query);
       reader reader1;
       while(rs.next()){
           
           reader1=new reader(rs.getString("nom"),rs.getString("prenom"),Integer.parseInt(rs.getString("phonenumber")),rs.getString("cin"),rs.getString("email"),Integer.parseInt(rs.getString("status")),Integer.parseInt(rs.getString("book_count")));
           readers.add(reader1);
       }
       return(readers);
       
    }  
        public final void showread() {
    try {
        ArrayList<reader> readers = getreadList();
        String[] columnName = {"cin", "firstname", "lastname", "phonenumber", "email","status","book_count"};
        Object[][] rows = new Object[readers.size()][7];
        for (int i = 0; i < readers.size(); i++) {
            rows[i][0] = readers.get(i).getcin();
            rows[i][1] = readers.get(i).getfirstname();
            rows[i][2] = readers.get(i).getlastname();
            rows[i][3] =readers.get(i).getphone(); 
            rows[i][4] =readers.get(i).getemail();
            rows[i][6] =readers.get(i).getbook();
            if(readers.get(i).getstatues()==1){
                rows[i][5] ="has right to issue book";
                
            }
            else{
                rows[i][5] ="no right to issue book";
                
            }
               
            

        }
        
        tableread T = new tableread(rows, columnName);
        members.setModel(T);
        members.setRowHeight(60);
        members.getColumnModel().getColumn(4).setPreferredWidth(100);
    } catch (SQLException ex) {
        Logger.getLogger(managelecteurs.class.getName()).log(Level.SEVERE, null, ex);
    }
}

        
    public final void addPlaceholderStyle(JTextField textField){
        Font font=textField.getFont();
        font=font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
        
        
        
    }

    public void removePlaceholderStyle(JTextField textField){
        Font font=textField.getFont();
        font=font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
        
  
        
    }
    public void close(){
        WindowEvent closeWindow=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        members = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        seachev = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phonenumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        status1 = new javax.swing.JTextField();
        bookcount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(13, 27, 43));
        jPanel3.setForeground(new java.awt.Color(13, 27, 43));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile (2).png"))); // NOI18N
        jLabel8.setText("Manage members");

        members.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        members.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        members.setShowGrid(true);
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(members);

        search.setText("Search  member");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        seachev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-interface-symbol.png"))); // NOI18N
        seachev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seachevActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(67, 91, 123));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CIN:");

        cin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cin.setText(" ex:10023512");
        cin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFocusLost(evt);
            }
        });
        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FirstName:");

        lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname.setText("ex: Brown");
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone  Number:");

        phonenumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phonenumber.setText("ex: 22222222");
        phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonenumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenumberFocusLost(evt);
            }
        });
        phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("ex: book@gmail.com");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(67, 91, 123));
        update.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(67, 91, 123));
        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Rewind_48px.png"))); // NOI18N
        back.setText("Back");
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname.setText("ex: Alex");
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LastName:");

        add.setBackground(new java.awt.Color(67, 91, 123));
        add.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus (1).png"))); // NOI18N
        add.setText(" Add");
        add.setMaximumSize(new java.awt.Dimension(112, 39));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add a member");

        delete.setBackground(new java.awt.Color(67, 91, 123));
        delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remove.png"))); // NOI18N
        delete.setText("Delete");
        delete.setMaximumSize(new java.awt.Dimension(112, 39));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        status1.setText("1");

        bookcount.setText("5");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Book_count: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phonenumber, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(update)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bookcount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookcount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(293, 293, 293))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seachev, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seachev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean isNumeric(String str) { 
        
    return (str.matches("[-+]?[0-9]*\\.?[0-9]+"));  
   
}  

    public void ouvragesEnPossession(int cin) throws Exception {
        String query = "SELECT b.titre, b.auteur " +
                       "FROM emprunt e " +
                       "JOIN Books b ON e.isbn = b.ISBN " +
                       "WHERE e.CIN = ? and e.status=0";
        
        try {
            Connection connection = ConnectionProvider.getCon();
            PreparedStatement statement = connection.prepareStatement(query); 
            statement.setInt(1, cin);
            ResultSet resultSet = statement.executeQuery();
            String mess="";
            if(resultSet.next()){
                mess=mess+"member with the CIN "+Integer.toString(cin)+" issued:\n ";
                while (resultSet.next()) {
                String titre = resultSet.getString("titre");
                String auteur = resultSet.getString("auteur");
                mess=mess+"Book Name: " + titre + ", Author " + auteur+"\n";
            }
                
               
                
            }
            else{
                        throw(new  Exception("Error:not found"));
            }
            String query2 = "SELECT b.titre, b.auteur, COUNT(*) AS nombre_demandes " +
                       "FROM emprunt e " +
                       "JOIN Books b ON e.isbn = b.ISBN " +
                       "WHERE e.CIN = ? " +
                       "GROUP BY b.titre, b.auteur " +
                       "ORDER BY COUNT(*) DESC " +
                       "LIMIT 1";

        
    
            statement = connection.prepareStatement(query2); 
            statement.setInt(1, cin);
            resultSet = statement.executeQuery();
            if (resultSet.next()) {
                mess=mess+"the most requested Book: \n";
                String titre = resultSet.getString("titre");
                String auteur = resultSet.getString("auteur");
                int nombreDemandes = resultSet.getInt("nombre_demandes");
                mess=mess+"Book Name: " + titre + ", Author " + auteur+"Number of Requests "+ (nombreDemandes);
                
            
   
            
        }
        JOptionPane.showMessageDialog(null, mess);
                }
        catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
        }
        
    }
public static boolean isemail(String email){
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
}
    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed

    }//GEN-LAST:event_cinActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed
    public boolean updateread(){
        boolean isupdate = false;
        
         reader member=new reader(firstname.getText(),lastname.getText(),Integer.parseInt(phonenumber.getText()),cin.getText(),email.getText(),Integer.parseInt(status1.getText()),Integer.parseInt(bookcount.getText()));
           
         try{
             Connection con = ConnectionProvider.getCon();
        String sql = "UPDATE lecteur SET nom=?, prenom=?, phonenumber=?,book_count=?, email=?, status=? WHERE cin=?;";

        System.out.println(sql);

        PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setString(1, member.getfirstname());
        pst.setString(2, member.getlastname());
        pst.setInt(3, member.getphone());
        pst.setInt(4,member.getbook() );
        pst.setString(5, member.getemail());
        if(member.getstatues() == 1){
             pst.setBoolean(6,true );
            
        }
        else{
            pst.setBoolean(6,false);
            
        }
       
        pst.setString(7, member.getcin());
        
        int rowcount=pst.executeUpdate();
        
        if(rowcount>0){
            isupdate=true;
            
        }   
        else{
            isupdate=false;
        }
 
        
              
             
         }
         catch(Exception e){
             e.printStackTrace();
             
         }
         return(isupdate);
       
         
        
    }
        
        public boolean deleteread(){
        boolean isdelete = false;
         reader member=new reader(firstname.getText(),lastname.getText(),Integer.parseInt(phonenumber.getText()),cin.getText(),email.getText(),Integer.parseInt(status1.getText()),Integer.parseInt(bookcount.getText()));
          
         try{
             Connection con = ConnectionProvider.getCon();
        String sql = "delete from lecteur  WHERE cin=?;";
        
        

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, member.getcin());
        
        int rowcount=pst.executeUpdate();
        
        if(rowcount>0){
            isdelete=true;
            
        }   
        else{
            isdelete=false;
        }
 
        
              
             
         }
         catch(Exception e){
             e.printStackTrace();
             
         }
         return(isdelete);
       
         
        
    }
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         try {
             

            if((!isNumeric(status1.getText())) ||(Integer.parseInt(status1.getText())!= 1 && Integer.parseInt(status1.getText())!= 0)){
           
                throw(new Exception("status must be 0 or 1 "));
            }
            if((!isNumeric(bookcount.getText())) ||(!(Integer.parseInt(bookcount.getText())<=5 && Integer.parseInt(bookcount.getText())>=0 ))){
           
                throw(new Exception("0<=book_count<=5"));
            }
            if(firstname.getText().trim().equals("") || firstname.getText().equals("ex: Alex") ){
                throw(new Exception("you must give a firstname"));
            }
            if(email.getText().trim().equals("") || email.getText().equals("ex: book@gmail.com") || (!isemail(email.getText())) ){
                throw(new Exception("you must give a valid email"));
            }
            if(lastname.getText().trim().equals("") || lastname.getText().equals("ex: Brown") ){
                throw(new Exception("you must give a lastname"));
            }
            if(cin.getText().trim().equals("") || !isNumeric(cin.getText())){
                throw(new Exception("give Cin must ba a number "));
            }
            if(phonenumber.getText().trim().equals("") ||  !isNumeric(phonenumber.getText()) || cin.getText().equals("ex: 22222222")){
                throw(new Exception("phone number must ba a number "));
            }
                
           
         if(updateread()) {
             JOptionPane.showMessageDialog(this, "successful update");
             cin.setEnabled(true);
             email.setText("ex: book@gmail.com");
            phonenumber.setText("ex: 22222222");
            lastname.setText("ex: Brown");
            firstname.setText("ex: Alex");
            cin.setText(" ex:10023512");
            status1.setText("1");
            bookcount.setText("5");
             addPlaceholderStyle(cin);
             addPlaceholderStyle(firstname);
             addPlaceholderStyle(lastname);
            addPlaceholderStyle(email);
            addPlaceholderStyle(phonenumber);
            addPlaceholderStyle(search);
            addPlaceholderStyle(status1);
            status1.setEnabled(false);
            addPlaceholderStyle(bookcount);
            bookcount.setEnabled(false);
             
             showread();
             
         }
         else{
             JOptionPane.showMessageDialog(this, "failed update");
             cin.setEnabled(true);
              phonenumber.setText("ex: 22222222");
            lastname.setText("ex: Brown");
            firstname.setText("ex: Alex");
            cin.setText(" ex:10023512");
            status1.setText("1");
            bookcount.setText("5");
             addPlaceholderStyle(cin);
             addPlaceholderStyle(firstname);
             addPlaceholderStyle(lastname);
            addPlaceholderStyle(email);
            addPlaceholderStyle(phonenumber);
            addPlaceholderStyle(search);
            addPlaceholderStyle(status1);
            status1.setEnabled(false);
            addPlaceholderStyle(bookcount);
            bookcount.setEnabled(false);
             
         } }
        catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        finally{
             cin.setEnabled(true);
             addPlaceholderStyle(cin);
        addPlaceholderStyle(firstname);
        addPlaceholderStyle(lastname);
        addPlaceholderStyle(email);
        addPlaceholderStyle(phonenumber);
        addPlaceholderStyle(search);
        addPlaceholderStyle(status1);
        status1.setEnabled(false);
        addPlaceholderStyle(bookcount);
        bookcount.setEnabled(false);
         }
    
            

    }//GEN-LAST:event_updateActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
       
    }//GEN-LAST:event_firstnameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
              try{
                  
                  
            if(firstname.getText().trim().equals("") || firstname.getText().equals("ex: Alex") ){
                throw(new Exception("you must give a firstname"));
            }
            if(email.getText().trim().equals("") || email.getText().equals("ex: book@gmail.com") || (!isemail(email.getText())) ){
                throw(new Exception("you must give a valid email"));
            }
            if(lastname.getText().trim().equals("") || lastname.getText().equals("ex: Brown") ){
                throw(new Exception("you must give a lastname"));
            }
            if(cin.getText().trim().equals("") || !isNumeric(cin.getText())){
                throw(new Exception("give Cin must ba a number "));
            }
            if(phonenumber.getText().trim().equals("") ||  !isNumeric(phonenumber.getText()) || cin.getText().equals("ex: 22222222")){
                throw(new Exception("phone number must ba a number "));
            }

            reader member=new reader(firstname.getText(),lastname.getText(),Integer.parseInt(phonenumber.getText()),cin.getText(),email.getText(),1,5);
            readDao.save(member);

              phonenumber.setText("ex: 22222222");
              email.setText("ex: book@gmail.com");
            lastname.setText("ex: Brown");
            firstname.setText("ex: Alex");
            cin.setText(" ex:10023512");

             addPlaceholderStyle(cin);
             addPlaceholderStyle(firstname);
             addPlaceholderStyle(lastname);
            addPlaceholderStyle(email);
            addPlaceholderStyle(phonenumber);
            addPlaceholderStyle(search);

           
            
            showread();

           
            

            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_addActionPerformed
    public void cleartable(){
        DefaultTableModel model=(DefaultTableModel)members.getModel();
        model.setRowCount(0);
    }
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         try{   
            
         if(deleteread()){
             
             cin.setEnabled(true);
              phonenumber.setText("ex: 22222222");
              email.setText("ex: book@gmail.com");
            lastname.setText("ex: Brown");
            firstname.setText("ex: Alex");
            cin.setText(" ex:10023512");
            status1.setText("1");
            bookcount.setText("5");
             addPlaceholderStyle(cin);
             addPlaceholderStyle(firstname);
             addPlaceholderStyle(lastname);
            addPlaceholderStyle(email);
            addPlaceholderStyle(phonenumber);
            addPlaceholderStyle(search);
            addPlaceholderStyle(status1);
            status1.setEnabled(false);
            addPlaceholderStyle(bookcount);
            bookcount.setEnabled(false);
         
           JOptionPane.showMessageDialog(this, "successful delete");
             
             showread();
             
         }
         else{
             cin.setEnabled(true);
              phonenumber.setText("ex: 22222222");
            lastname.setText("ex: Brown");
            firstname.setText("ex: Alex");
            cin.setText(" ex:10023512");
            status1.setText("1");
            bookcount.setText("5");
             addPlaceholderStyle(cin);
             email.setText("ex: book@gmail.com");
             addPlaceholderStyle(firstname);
             addPlaceholderStyle(lastname);
            addPlaceholderStyle(email);
            addPlaceholderStyle(phonenumber);
            addPlaceholderStyle(search);
            addPlaceholderStyle(status1);
            status1.setEnabled(false);
            addPlaceholderStyle(bookcount);
            bookcount.setEnabled(false);
             JOptionPane.showMessageDialog(this, "failed delete");
             
         } 
}
         
        catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
    
            

    

        
    }//GEN-LAST:event_deleteActionPerformed

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained

        if(firstname.getText().equals("ex: Alex")){
            firstname.setText(null);
            firstname.requestFocus();
            removePlaceholderStyle(firstname);
        }
    }//GEN-LAST:event_firstnameFocusGained

    private void cinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusGained
        if(cin.getText().equals(" ex:10023512")){
            cin.setText(null);
            cin.requestFocus();
            removePlaceholderStyle(cin);
        }
    }//GEN-LAST:event_cinFocusGained

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
        if(cin.getText().length() ==0){
            addPlaceholderStyle(cin);
            cin.setText(" ex:10023512");
        }
    }//GEN-LAST:event_cinFocusLost

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
         if(firstname.getText().length() ==0){
            addPlaceholderStyle(firstname);
            firstname.setText("ex: Alex");
        }
    }//GEN-LAST:event_firstnameFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        if(lastname.getText().equals("ex: Brown")){
            lastname.setText(null);
            lastname.requestFocus();
            removePlaceholderStyle(lastname);
        }
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        if(lastname.getText().length() ==0){
            addPlaceholderStyle(lastname);
            lastname.setText("ex: Brown");
        }
    }//GEN-LAST:event_lastnameFocusLost

    private void phonenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumberFocusGained
        if(phonenumber.getText().equals("ex: 22222222")){
            phonenumber.setText(null);
            phonenumber.requestFocus();
            removePlaceholderStyle(phonenumber);
        }
    }//GEN-LAST:event_phonenumberFocusGained

    private void phonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenumberFocusLost
       if(phonenumber.getText().length() ==0){
            addPlaceholderStyle(phonenumber);
            phonenumber.setText("ex: 22222222");
        }
    }//GEN-LAST:event_phonenumberFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(email.getText().equals("ex: book@gmail.com")){
            email.setText(null);
            email.requestFocus();
            removePlaceholderStyle(email);
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(email.getText().length() ==0){
            addPlaceholderStyle(email);
            email.setText("ex: book@gmail.com");
        }
    }//GEN-LAST:event_emailFocusLost

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // home page
    }//GEN-LAST:event_backActionPerformed

    private void seachevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seachevActionPerformed
        try {

            if(search.getText().trim().equals("") || !isNumeric(search.getText())){
                throw(new Exception("give Cin must ba a number "));
            }
            int cin1=Integer.parseInt(search.getText());
            ouvragesEnPossession(cin1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_seachevActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        if(search.getText().length() ==0){
            addPlaceholderStyle(search);
            search.setText("Search  member");
        }
    }//GEN-LAST:event_searchFocusLost

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        if(search.getText().equals("Search  member")){
            search.setText(null);
            search.requestFocus();
            removePlaceholderStyle(search);
        }
    }//GEN-LAST:event_searchFocusGained

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersMouseClicked
        cin.setEnabled(false);
        status1.setEnabled(true);
        bookcount.setEnabled(true);
        int rowNo=members.getSelectedRow();
        TableModel model=members.getModel();
        cin.setText(model.getValueAt(rowNo, 0).toString());
        firstname.setText(model.getValueAt(rowNo, 1).toString());
        lastname.setText(model.getValueAt(rowNo, 2).toString());
        phonenumber.setText(model.getValueAt(rowNo, 3).toString());
        email.setText(model.getValueAt(rowNo, 4).toString());
        bookcount.setText(model.getValueAt(rowNo, 6).toString());
        if(model.getValueAt(rowNo, 5).toString().equals("has right to issue book")){
            status1.setText("1");
            
        }
        else{
            status1.setText("0");
            
        }
        
    }//GEN-LAST:event_membersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managelecteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managelecteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managelecteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managelecteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managelecteurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField bookcount;
    private javax.swing.JTextField cin;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTable members;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JButton seachev;
    private javax.swing.JTextField search;
    private javax.swing.JTextField status1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
